"""Domain entities — rich objects with invariants, no infra deps."""

from __future__ import annotations

from dataclasses import dataclass, field
from typing import Sequence

from raglab.domain.enums import DatasetSplit, PipelineStrategy, QuestionState
from raglab.domain.errors import (
    InvalidIdentifierError,
    MissingProvenanceError,
)
from raglab.domain.value_objects import (
    ChunkId,
    Citation,
    IntegrityDigest,
    MetricResult,
    RunId,
)


@dataclass(frozen=True, slots=True)
class Corpus:
    """A versioned corpus with integrity fingerprint.

    Invariants:
    - corpus_id must be non-empty
    - fingerprint must be valid IntegrityDigest
    - total_pages must be non-negative
    """

    corpus_id: str
    name: str
    fingerprint: IntegrityDigest
    total_pages: int
    total_documents: int

    def __post_init__(self) -> None:
        if not self.corpus_id or not self.corpus_id.strip():
            raise InvalidIdentifierError("Corpus.corpus_id")
        if self.total_pages < 0:
            raise ValueError("total_pages must be non-negative")
        if self.total_documents < 0:
            raise ValueError("total_documents must be non-negative")


@dataclass(frozen=True, slots=True)
class Document:
    """A source document within a corpus."""

    document_id: str
    filename: str
    fingerprint: IntegrityDigest
    page_count: int

    def __post_init__(self) -> None:
        if not self.document_id or not self.document_id.strip():
            raise InvalidIdentifierError("Document.document_id")
        if self.page_count < 0:
            raise ValueError("page_count must be non-negative")


@dataclass(frozen=True, slots=True)
class Chunk:
    """A text chunk with provenance to source document.

    Invariants:
    - chunk_id must be valid
    - document_id must be non-empty (provenance required)
    - start_page must be non-negative
    """

    chunk_id: ChunkId
    document_id: str
    text: str
    start_page: int
    end_page: int

    def __post_init__(self) -> None:
        if not self.document_id or not self.document_id.strip():
            raise MissingProvenanceError()
        if self.start_page < 0 or self.end_page < 0:
            raise ValueError("page numbers must be non-negative")
        if self.end_page < self.start_page:
            raise ValueError("end_page must be >= start_page")


@dataclass(frozen=True, slots=True)
class Query:
    """A query in the benchmark with split assignment."""

    query_id: str
    text: str
    split: DatasetSplit

    def __post_init__(self) -> None:
        if not self.query_id or not self.query_id.strip():
            raise InvalidIdentifierError("Query.query_id")
        if not self.text or not self.text.strip():
            raise InvalidIdentifierError("Query.text")


@dataclass(frozen=True, slots=True)
class QuestionSet:
    """A collection of queries for a specific split."""

    split: DatasetSplit
    queries: tuple[Query, ...]

    def __post_init__(self) -> None:
        for q in self.queries:
            if q.split != self.split:
                raise ValueError(
                    f"Query '{q.query_id}' split {q.split} != set split {self.split}"
                )


@dataclass(frozen=True, slots=True)
class RetrievedEvidence:
    """A single retrieved piece of evidence with provenance.

    Invariants:
    - chunk_id must be valid (provenance required)
    - rank must be positive
    - score must be finite
    """

    chunk_id: ChunkId
    document_id: str
    text: str
    rank: int
    score: float

    def __post_init__(self) -> None:
        if not self.document_id or not self.document_id.strip():
            raise MissingProvenanceError()
        if self.rank < 1:
            raise ValueError("rank must be >= 1")
        import math

        if not math.isfinite(self.score):
            raise ValueError("score must be finite")


@dataclass(frozen=True, slots=True)
class RetrievalResult:
    """Results of retrieval for a single query."""

    query_id: str
    strategy: PipelineStrategy
    evidence: tuple[RetrievedEvidence, ...]

    def __post_init__(self) -> None:
        if not self.query_id or not self.query_id.strip():
            raise InvalidIdentifierError("RetrievalResult.query_id")


@dataclass(frozen=True, slots=True)
class GeneratedAnswer:
    """An answer generated by the LLM with abstention support.

    Invariants:
    - abstained answers are distinguishable from normal answers
    - citations provide provenance
    """

    query_id: str
    text: str
    abstained: bool
    citations: tuple[Citation, ...]

    def __post_init__(self) -> None:
        if not self.query_id or not self.query_id.strip():
            raise InvalidIdentifierError("GeneratedAnswer.query_id")


@dataclass(frozen=True, slots=True)
class EvaluationResult:
    """Evaluation outcome for a single query across metrics."""

    query_id: str
    strategy: PipelineStrategy
    metrics: tuple[MetricResult, ...]

    def __post_init__(self) -> None:
        if not self.query_id or not self.query_id.strip():
            raise InvalidIdentifierError("EvaluationResult.query_id")


@dataclass(frozen=True, slots=True)
class ArtifactManifest:
    """Manifest for an experiment artifact with integrity digest."""

    artifact_id: str
    artifact_type: str
    fingerprint: IntegrityDigest

    def __post_init__(self) -> None:
        if not self.artifact_id or not self.artifact_id.strip():
            raise InvalidIdentifierError("ArtifactManifest.artifact_id")


@dataclass(frozen=True, slots=True)
class Checkpoint:
    """A resumable checkpoint tied to specific config and corpus.

    Invariants:
    - run_id must be valid
    - corpus_fingerprint ties checkpoint to specific corpus version
    - config_fingerprint ties checkpoint to specific configuration
    """

    run_id: RunId
    corpus_fingerprint: IntegrityDigest
    config_fingerprint: IntegrityDigest
    completed_query_ids: frozenset[str] = field(default_factory=frozenset)
    question_states: dict[str, QuestionState] = field(default_factory=dict)

    def __post_init__(self) -> None:
        # Validate that question_states is not mutable through the frozen dataclass
        # by ensuring it's a proper dict (will be shallow-frozen by frozen=True)
        pass

    def is_compatible(
        self,
        corpus_fp: IntegrityDigest,
        config_fp: IntegrityDigest,
    ) -> bool:
        """Check if checkpoint matches current run configuration."""
        return (
            self.corpus_fingerprint == corpus_fp
            and self.config_fingerprint == config_fp
        )


@dataclass(frozen=True, slots=True)
class ExperimentRun:
    """Top-level experiment run combining strategy, corpus, and config."""

    run_id: RunId
    strategy: PipelineStrategy
    corpus_id: str
    split: DatasetSplit

    def __post_init__(self) -> None:
        if not self.corpus_id or not self.corpus_id.strip():
            raise InvalidIdentifierError("ExperimentRun.corpus_id")
